### ISSUE TITLE
What could be better in the app?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/world-glacier-explorer#7]
Based on @linznicholson and @pat-schmitt 's use of the Explorer in the lecture, what could be better with the app?

Here are some of my suggestions, let me know if you have more ideas:

- [ ] Zooming in region makes it harder to see glaciers (https://github.com/OGGM/world-glacier-explorer/issues/4) (Also noted by @zschirmeister )
- [ ] The five-button interface is slightly confusing for the user (https://github.com/OGGM/world-glacier-explorer/issues/5)
- [ ] asl and bsl abbreviation explanations not visible enough? (https://github.com/OGGM/world-glacier-explorer/issues/6)
- [ ] Lasso tool for selection in addition to box (https://github.com/OGGM/world-glacier-explorer/issues/8)
